trainer:
  min_epochs: 15
  max_epochs: 100

model:
  class_path: ObjectDetectionTask
  init_args:
    model: "faster-rcnn"
    backbone: "resnet50"
    weights: True
    num_classes: 11
    lr: 3.0e-5
    patience: 10
data:
  class_path: VHR10DataModule
  init_args:
    batch_size: 2 #4 #2
    num_workers: 31 #16 #31 #0
    patch_size: 512
  dict_kwargs:
    root: "/home/ash1/Projects/torchgeo/data/vhr10"
